### ISSUE TITLE
Unable to send LINE message

### ISSUE THREAD

**Issue by wallyatkins** [appleboy/line-action#1]
`linebot: APIError 400 The property, 'to', in the request body is invalid (line: -, column: -)`

Here is my YML:

```
on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  build:
    name: send rss message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/line-action@master
      with:
        secret: ${{ secrets.LINE_CHANNEL_SECRET }}
        token: ${{ secrets.LINE_CHANNEL_TOKEN }}
        group: ${{ secrets.LINE_GROUP_ID }}
        message: line message from GitHub Actions - ${{on.rss.outputs.title}}
```
